name: Workflow Name 

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main] 

env:
  ENV_TYPE: production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "[client] Install dependencies"
        run: |
          yarn install --frozen-lockfile

      - name: "[client] Run ESLint"
        run: |
          yarn eslint 'src/**/*.{ts,tsx}' --ext .tsx

      - name: "[client] Run Prettier"
        run: |
          yarn prettier --config .prettierrc 'src/**/*.{ts,tsx}' --write

      - name: "[client] Run TypeScript compiler"
        run: |
          yarn tsc

      - name: "[client] Build"
        run: |
          yarn build